### ISSUE TITLE
Evaluation is incorrect

### ISSUE THREAD

**Issue by adolfintel** [RhythmLunatic/Delta-NEX-Rebirth#31] opened 2018-09-05 06:33 UTC
Stepmania 5.0.12, gamemode pump.
I did all perfects in a song and it gives me 91%? Any way to change this?
![photo_2018-09-04_23-18-21](https://user-images.githubusercontent.com/16307689/45075119-58961e80-b0e6-11e8-84d2-4ed10c877bd9.jpg)

**Comment by RhythmLunatic** [comment] 2018-09-11 03:39
This is a known StepMania bug and also a duplicate of issue #8. For now, it's beyond my ability to fix.

https://github.com/stepmania/stepmania/issues/1089

**Closed as completed** 2018-09-11 03:41 UTC
Labels: bug, duplicate

**Comment by adolfintel** [comment] 2018-09-11 05:19
What a nasty bug, thanks for the info
